// demo-app/resources/js/Pages/ComponentThatUsesModalInstance.vue
<script setup>
import { useModal } from '@inertiaui/modal-vue'

const modal = useModal()

if (modal) {
    const { props } = useModal()
    console.log(props.roles)
}
</script>

<template>
    <div v-if="modal">
        <button @click="modal.close()">Close Modal with index {{ modal.index }}</button>
    </div>
</template>

// demo-app/resources/js/Pages/ComponentThatUsesModalInstance.svelte
<script>
    import { useModal } from '@inertiaui/modal-svelte'

    const modal = useModal()

    if (modal) {
        const { props } = useModal()
        console.log(props.roles)
    }
</script>

{#if modal}
    <div>
        <button onclick={modal.close}>Close Modal with index {modal.index}</button>
    </div>
{/if}
