// demo-app/resources/js/Pages/Header.svelte
<script>
    import Container from './Container.svelte'
    import { ModalLink } from '@inertiaui/modal-svelte'
</script>

<Container>
    <div class="flex justify-between">
        <h2 class="text-lg font-medium text-gray-900">Header</h2>
    </div>

    <ModalLink
        dusk="modal-link"
        href="/roles/create"
        headers={{ 'X-Test-Header': 'Test Header Value' }}
    >
        Open Modal
    </ModalLink>
</Container>

// demo-app/resources/js/Pages/Header.jsx
import { ModalLink } from 'inertiaui/modal';
import Container from './Container';

export default function Header() {
    return (
        <Container>
            <div className="flex justify-between">
                <h2 className="text-lg font-medium text-gray-900">Header</h2>
            </div>
            <ModalLink
                dusk="modal-link"
                href="/roles/create"
                headers={{ 'X-Test-Header': 'Test Header Value' }}
            >
                Open Modal
            </ModalLink>
        </Container>
    );
}
