// demo-app/resources/js/Pages/LocalWithProps.jsx
import { Modal, useModalStack } from '@inertiaui/modal-react'

import Container from './Container'

export default function LocalWithProps() {
    const { visitModal } = useModalStack()

    function openWithProps() {
        visitModal('#local-props', {
            props: {
                message: 'Hello from props!',
                count: 42,
            },
        })
    }

    return (
        <>
            <Container>
                <div className="flex flex-col items-start gap-4">
                    <h2 className="text-lg font-medium text-gray-900">Local Modal with Props</h2>

                    <button onClick={openWithProps} data-testid="open-with-props">
                        Open Local Modal with Props
                    </button>
                </div>
            </Container>

            <Modal name="local-props">
                {({ message, count }) => (
                    <div className="p-4">
                        <p data-testid="modal-message">{message}</p>
                        <p data-testid="modal-count">{count}</p>
                    </div>
                )}
            </Modal>
        </>
    )
}

// demo-app/resources/js/Pages/LocalWithProps.vue
<script setup>
import Container from './Container.vue'
import { Modal, useModal, visitModal } from '@inertiaui/modal-vue'
import { ref } from 'vue'

const receivedMessage = ref('')

function openWithProps() {
    visitModal('#local-props', {
        props: {
            message: 'Hello from props!',
            count: 42,
        },
    })
}
</script>

<template>
    <Container>
        <div class="flex flex-col items-start gap-4">
            <h2 class="text-lg font-medium text-gray-900">Local Modal with Props</h2>

            <button @click="openWithProps" data-testid="open-with-props">
                Open Local Modal with Props
            </button>

            <p data-testid="received-message">{{ receivedMessage }}</p>
        </div>
    </Container>

    <Modal name="local-props" v-slot="{ message, count }">
        <div class="p-4">
            <p data-testid="modal-message">{{ message }}</p>
            <p data-testid="modal-count">{{ count }}</p>
        </div>
    </Modal>
</template>
