// demo-app/resources/js/Pages/Local.svelte
<script>
    import Container from './Container.svelte'
    import { Modal, ModalLink } from '@inertiaui/modal-svelte'

    let modalRef = $state()

    function closeModal() {
        modalRef.close()
    }

    function alertModalId() {
        alert(modalRef.getId())
    }
</script>

<Container>
    <div class="flex justify-between">
        <h2 class="text-lg font-medium text-gray-900">Local</h2>

        <ModalLink href="#local" class="px-2 py-1 text-xs font-medium text-indigo-600 bg-indigo-100 rounded-md">
            Open Local Modal
        </ModalLink>
    </div>
</Container>

<Modal name="local" bind:this={modalRef}>
    This is a local modal

    <ModalLink href="/roles/create">
        Create Role
    </ModalLink>

    <button onclick={closeModal}>
        Close Modal through Ref
    </button>

    <button onclick={alertModalId}>
        Alert Modal ID
    </button>
</Modal>

// demo-app/resources/js/Pages/Local.vue
<script setup>
import { Modal, ModalLink } from '@inertiaui/modal-vue'
import { ref } from 'vue'

import Container from './Container.vue'

const modalRef = ref(null)

function closeModal() {
    modalRef.value.close()
}

function alertModalId() {
    alert(modalRef.value.id)
}
</script>

<template>
    <Container>
        <div class="flex justify-between">
            <h2 class="text-lg font-medium text-gray-900">Local</h2>

            <ModalLink href="#local" class="rounded-md bg-indigo-100 px-2 py-1 text-xs font-medium text-indigo-600"> Open Local Modal </ModalLink>
        </div>
    </Container>

    <Modal name="local" ref="modalRef">
        This is a local modal

        <ModalLink href="/roles/create"> Create Role </ModalLink>

        <button @click="closeModal">Close Modal through Ref</button>

        <button @click="alertModalId">Alert Modal ID</button>
    </Modal>
</template>
