// demo-app/resources/js/Pages/ModalPropsIgnoreFirstLoad.vue
<script setup>
import { Deferred, Modal, WhenVisible } from '@inertiaui/modal-vue'
import { ref } from 'vue'

defineProps({
    deferA: String,
    deferB: String,
    lazy: String,
    optional: String,
})

const visible = ref(false)
</script>

<template>
    <Modal v-slot="{ reload }">
        <Deferred :data="['deferA', 'deferB']">
            <template #fallback>
                <p data-testid="defer">Loading defer...</p>
            </template>

            <p data-testid="defer" class="text-green-500">
                {{ deferA }}
            </p>

            <p data-testid="defer-b" class="text-green-500">
                {{ deferB }}
            </p>
        </Deferred>

        <div class="mt-8">
            <button type="button" @click="reload({ only: ['lazy'] })" class="underline">Load lazy</button>

            <p data-testid="lazy" :class="lazy ? 'text-green-500' : ''">
                {{ lazy ?? 'No lazy data loaded' }}
            </p>
        </div>

        <div class="mt-8">
            <button type="button" @click="visible = !visible" class="underline">Make {{ visible ? 'invisible' : 'visible' }}</button>

            <div v-show="visible">
                <WhenVisible data="optional" always>
                    <template #fallback>
                        <p data-testid="optional">Loading optional...</p>
                    </template>

                    <p data-testid="optional" class="text-green-500">
                        {{ optional }}
                    </p>
                </WhenVisible>
            </div>
        </div>
    </Modal>
</template>

// demo-app/resources/js/Pages/ModalPropsIgnoreFirstLoad.jsx
import { Modal, Deferred, WhenVisible } from '@inertiaui/modal-react'
import { useState } from 'react';

export default function ModalPropsIgnoreFirstLoad({ deferA, deferB, lazy, optional }) {
    const [visible, setVisible] = useState(false);

    return (
        <Modal>
            {({ reload }) => (
                <>
                    <Deferred
                        data={['deferA', 'deferB']}
                        fallback={<p data-testid="defer">Loading defer...</p>}
                    >
                        <p data-testid="defer" className="text-green-500">
                            {deferA}
                        </p>
                        <p data-testid="defer-b" className="text-green-500">
                            {deferB}
                        </p>
                    </Deferred>

                    <div className="mt-8">
                        <button
                            type="button"
                            onClick={() => reload({ only: ["lazy"] })}
                            className="underline"
                        >
                            Load lazy
                        </button>
                        <p data-testid="lazy" className={lazy ? "text-green-500" : ""}>
                            {lazy ?? "No lazy data loaded"}
                        </p>
                    </div>

                    <div className="mt-8">
                        <button
                            type="button"
                            onClick={() => setVisible(!visible)}
                            className="underline"
                        >
                            Make {visible ? "invisible" : "visible"}
                        </button>
                        <div className={!visible ? "hidden" : ""}>
                            <WhenVisible
                                data="optional"
                                always={true}
                                fallback={<p data-testid="optional">Loading optional...</p>}
                            >
                                <p data-testid="optional" className="text-green-500">
                                    {optional}
                                </p>
                            </WhenVisible>
                        </div>
                    </div>
                </>
            )}
        </Modal>
    )
}
