// demo-app/resources/js/Pages/ModalEvents.svelte
<script>
    import { Modal, ModalLink } from '@inertiaui/modal-svelte'

    function log(value) {
        console.log(value)
    }
</script>

<Modal
    onSuccess={() => log('success')}
    onBlur={() => log('blur')}
    onFocus={() => log('focus')}
    onClose={() => log('close')}
    onAfterLeave={() => log('after-leave')}
>
    <ModalLink href="/roles/create">
        Create role
    </ModalLink>
</Modal>

// demo-app/resources/js/Pages/ModalEvents.vue
<script setup>
import { Modal, ModalLink } from '@inertiaui/modal-vue'

function log(value) {
    console.log(value)
}
</script>

<template>
    <Modal
        @success="log('success')"
        @blur="log('blur')"
        @focus="log('focus')"
        @close="log('close')"
        @after-leave="log('after-leave')"
    >
        <ModalLink href="/roles/create">
            Create role
        </ModalLink>
    </Modal>
</template>
