// demo-app/resources/js/Pages/PostVisit.svelte
<script>
    import Container from './Container.svelte'
    import { ModalLink } from '@inertiaui/modal-svelte'
</script>

<Container>
    <div class="flex justify-between">
        <h2 class="text-lg font-medium text-gray-900">POST Visit</h2>

        <ModalLink href="/data" method="post" data={{'message': 'Hey there!'}} class="px-2 py-1 text-xs font-medium text-indigo-600 bg-indigo-100 rounded-md">
            Open POST Modal
        </ModalLink>
    </div>
</Container>

// demo-app/resources/js/Pages/PostVisit.jsx
import { ModalLink } from '@inertiaui/modal-react';
import Container from './Container';

export default function PostVisit() {
    return (
        <Container>
            <div className="flex justify-between">
                <h2 className="text-lg font-medium text-gray-900">POST Visit</h2>
                <ModalLink
                    href="/data"
                    method="post"
                    data={{ message: 'Hey there!' }}
                    className="px-2 py-1 text-xs font-medium text-indigo-600 bg-indigo-100 rounded-md"
                >
                    Open POST Modal
                </ModalLink>
            </div>
        </Container>
    );
}
