// demo-app/resources/js/Pages/ShowUser.vue
<script setup>
import { ModalLink } from '@inertiaui/modal-vue';
import Container from './Container.vue'
import * as InertiaVue from '@inertiajs/vue3';

const props = defineProps({
    user: Object,
    deferred: String
});
</script>

<template>
    <Container>
        <div class="">
            <p class="text-2xl font-medium text-gray-900">{{ user.name }}</p>
            <p class="text-xl text-gray-500">{{ user.email }}</p>
        </div>

        <component v-if="InertiaVue.Deferred" :is="InertiaVue.Deferred" data="deferred">
            <template #fallback>
                Loading...
            </template>

            <p data-testid="deferred">{{ deferred }}</p>
        </component>

        <p v-else data-testid="deferred">No Deferred Component</p>

        <ModalLink navigate as="button" :data-testid="'edit-user-' + user.id"
            :href="`/users/${user.id}/edit`"
            class="mt-4 px-3 py-2 text-sm font-medium text-indigo-600 bg-indigo-100 rounded-md">
            Edit
        </ModalLink>

    </Container>
</template>

// demo-app/resources/js/Pages/ShowUser.jsx
import * as InertiaReact from '@inertiajs/react'
import { ModalLink } from '@inertiaui/modal-react'

import Container from './Container'

export default function UserProfile({ user, deferred }) {
    return (
        <Container>
            <div className="">
                <p className="text-2xl font-medium text-gray-900">{user.name}</p>
                <p className="text-xl text-gray-500">{user.email}</p>
            </div>

            {InertiaReact.Deferred ? (
                <InertiaReact.Deferred data="deferred" fallback={<div>Loading...</div>}>
                    <p data-testid="deferred">{deferred}</p>
                </InertiaReact.Deferred>
            ) : (
                <p data-testid="deferred"> No Deferred Component</p>
            )}

            <ModalLink
                navigate
                as="button"
                data-testid={`edit-user-${user.id}`}
                href={`/users/${user.id}/edit`}
                className="mt-4 rounded-md bg-indigo-100 px-3 py-2 text-sm font-medium text-indigo-600"
            >
                Edit
            </ModalLink>
        </Container>
    )
}
