// demo-app/resources/js/Pages/Slideover.vue
<script setup>
import { Modal } from '@inertiaui/modal-vue';
</script>

<template>
     <Modal
        :close-button="false"
        :close-explicitly="true"
        max-width="2xl"
        padding-classes="p-8"
        panel-classes="bg-red-100 min-h-screen"
        position="left"
        :slideover="true"
     >
        <div class="flex justify-between">
            <h2 class="text-lg font-medium text-gray-900">Slideover with Props</h2>
        </div>
     </Modal>
</template>

// demo-app/resources/js/Pages/Slideover.jsx
import { Modal } from 'inertiaui/modal';

export default function Slideover() {
    return (
        <Modal
            closeButton={false}
            closeExplicitly={true}
            maxWidth="2xl"
            paddingClasses="p-8"
            panelClasses="bg-red-100 min-h-screen"
            position="left"
            slideover={true}
        >
            <div className="flex justify-between">
                <h2 className="text-lg font-medium text-gray-900">Slideover with Props</h2>
            </div>
        </Modal>
    );
}
