// svelte/src/lib/Deferred.svelte
<script>
    // https://github.com/inertiajs/inertia/blob/master/packages/svelte/src/components/Deferred.svelte
    import { getContext } from 'svelte'

    let { data, children, fallback } = $props()

    if (!data) {
        throw new Error('`<Deferred>` requires a `data` prop to be a string or array of strings')
    }

    const modalContext = getContext('modalContext')

    if (!modalContext) {
        throw new Error('Deferred component must be used inside a Modal component')
    }

    const keys = Array.isArray(data) ? data : [data]

    let allKeysAreAvailable = $derived(keys.every((key) => modalContext.props[key] !== undefined))
</script>

{#if allKeysAreAvailable}
    {@render children?.()}
{:else}
    {@render fallback?.()}
{/if}

// react/src/Deferred.jsx
// See: https://github.com/inertiajs/inertia/blob/48bcd21fb7daf467d0df1bfde2408f161f94a579/packages/react/src/Deferred.ts
import { useEffect, useState } from 'react'
import useModal from './useModal'

const Deferred = ({ children, data, fallback }) => {
    if (!data) {
        throw new Error('`<Deferred>` requires a `data` prop to be a string or array of strings')
    }

    const [loaded, setLoaded] = useState(false)
    const keys = Array.isArray(data) ? data : [data]
    const modalProps = useModal().props

    useEffect(() => {
        setLoaded(keys.every((key) => modalProps[key] !== undefined))
    }, [modalProps, keys])

    return loaded ? children : fallback
}

Deferred.displayName = 'InertiaModalDeferred'

export default Deferred
