// vue/src/ModalRoot.vue
<script setup>
import { onBeforeMount, onUnmounted, ref, watch } from 'vue'
import { router, usePage } from '@inertiajs/vue3'
import { useModalStack } from './modalStack'
import ModalRenderer from './ModalRenderer.vue'
import { default as Axios } from 'axios'
import { sameUrlPath } from './helpers'

const modalStack = useModalStack()

const isNavigating = ref(false)
const previousModalOnBase = ref(null)

onUnmounted(
    router.on('before', ($event) => {
        if (!sameUrlPath(window.location.href, $event.detail.visit.url)) {
            // Not navigating to the same base url
            return true
        }

        if ($event.detail.visit.replace) {
            // Prevent replacing again if we are already replacing
            return true
        }

        if (modalStack.stack.value.length !== 1) {
            // Only replace the first modal
            return true
        }

        if (!usePage().props?._inertiaui_modal) {
            // No modal on base
            return true
        }

        const {
            method,
            data,
            only,
            except,
            headers,
            errorBag,
            forceFormData,
            queryStringArrayFormat,
            async,
            showProgress,
            prefetch,
            fresh,
            reset,
            preserveUrl,
        } = $event.detail.visit

        router.visit($event.detail.visit.url, {
            replace: true,
            preserveScroll: true,
            preserveState: true,
            method,
            data,
            only,
            except,
            headers,
            errorBag,
            forceFormData,
            queryStringArrayFormat,
            async,
            showProgress,
            prefetch,
            fresh,
            reset,
            preserveUrl,
        })

        return false
    }),
)

onUnmounted(router.on('start', () => (isNavigating.value = true)))
onUnmounted(router.on('finish', () => (isNavigating.value = false)))
onUnmounted(
    router.on('navigate', ($event) => {
        const modalOnBase = $event.detail.page.props._inertiaui_modal

        if (!modalOnBase) {
            previousModalOnBase.value && modalStack.closeAll()
            return
        }

        previousModalOnBase.value = modalOnBase
        modalStack.setBaseUrl(modalOnBase.baseUrl)

        modalStack.pushFromResponseData(modalOnBase, {}, () => {
            if (!modalOnBase.baseUrl) {
                console.error('No base url in modal response data so cannot navigate back')
                return
            }

            if (!isNavigating.value && window.location.href !== modalOnBase.baseUrl) {
                router.visit(modalOnBase.baseUrl, {
                    preserveScroll: true,
                    preserveState: true,
                })
            }
        })
    }),
)

const axiosRequestInterceptor = (config) => {
    // A Modal is opened on top of a base route, so we need to pass this base route
    // so it can redirect back with the back() helper method...
    if (modalStack.stack.value.length) {
        config.headers['X-InertiaUI-Modal-Base-Url'] = modalStack.getBaseUrl()
    }

    return config
}

onBeforeMount(() => {
    Axios.interceptors.request.use(axiosRequestInterceptor)
})

onUnmounted(() => {
    Axios.interceptors.request.eject(axiosRequestInterceptor)
})

const $page = usePage()

watch(
    () => $page.props?._inertiaui_modal,
    (newModal, previousModal) => {
        if (newModal && previousModal && newModal.component === previousModal.component && sameUrlPath(newModal.url, previousModal.url)) {
            modalStack.stack.value[0]?.updateProps(newModal.props ?? {})
        }
    },
)
</script>

<template>
    <slot />

    <ModalRenderer
        v-if="modalStack.stack.value.length"
        :index="0"
    />
</template>

// react/src/ModalRoot.jsx
import { createElement, useEffect, useState } from 'react'
import { default as Axios } from 'axios'
import { except, only } from './helpers'
import { router, usePage } from '@inertiajs/react'
import { mergeDataIntoQueryString } from '@inertiajs/core'
import { createContext, useContext } from 'react'
import ModalRenderer from './ModalRenderer'
import { waitFor } from './helpers'
import { getConfig } from './config'

const ModalStackContext = createContext(null)
ModalStackContext.displayName = 'ModalStackContext'

let pageVersion = null
let resolveComponent = null
let baseUrl = null
let newModalOnBase = null
let localStackCopy = []

export const ModalStackProvider = ({ children }) => {
    const [stack, setStack] = useState([])
    const [localModals, setLocalModals] = useState({})

    const updateStack = (withStack) => {
        setStack((prevStack) => {
            const newStack = withStack([...prevStack])

            const isOnTopOfStack = (modalId) => {
                if (newStack.length < 2) {
                    return true
                }

                return (
                    newStack
                        .map((modal) => ({ id: modal.id, shouldRender: modal.shouldRender }))
                        .reverse()
                        .find((modal) => modal.shouldRender)?.id === modalId
                )
            }

            newStack.forEach((modal, index) => {
                newStack[index].onTopOfStack = isOnTopOfStack(modal.id)
                newStack[index].getParentModal = () => {
                    if (index < 1) {
                        // This is the first modal in the stack
                        return null
                    }

                    // Find the first open modal before this one
                    return newStack
                        .slice(0, index)
                        .reverse()
                        .find((modal) => modal.isOpen)
                }
                newStack[index].getChildModal = () => {
                    if (index === newStack.length - 1) {
                        // This is the last modal in the stack
                        return null
                    }

                    // Find the first open modal after this one
                    return newStack.slice(index + 1).find((modal) => modal.isOpen)
                }
            })

            return newStack
        })
    }

    useEffect(() => {
        localStackCopy = stack
    }, [stack])

    class Modal {
        constructor(component, response, config, onClose, afterLeave) {
            this.id = Modal.generateId()
            this.isOpen = false
            this.shouldRender = false
            this.listeners = {}

            this.component = component
            this.props = response.props
            this.response = response
            this.config = config
            this.onCloseCallback = onClose
            this.afterLeaveCallback = afterLeave

            this.index = -1 // Will be set when added to the stack
            this.getParentModal = () => null // Will be set in push()
            this.getChildModal = () => null // Will be set in push()
            this.onTopOfStack = true // Will be updated in push()
        }

        static generateId() {
            if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
                return `inertiaui_modal_${crypto.randomUUID()}`
            }
            // Fallback for environments where crypto.randomUUID is not available
            return `inertiaui_modal_${Date.now().toString(36)}_${Math.random().toString(36).substr(2, 9)}`
        }

        update = (config, onClose, afterLeave) => {
            updateStack((prevStack) =>
                prevStack.map((modal) => {
                    if (modal.id === this.id) {
                        modal.config = config
                        modal.onCloseCallback = onClose
                        modal.afterLeaveCallback = afterLeave
                    }
                    return modal
                }),
            )
        }

        show = () => {
            updateStack((prevStack) =>
                prevStack.map((modal) => {
                    if (modal.id === this.id && !modal.isOpen) {
                        modal.isOpen = true
                        modal.shouldRender = true
                    }
                    return modal
                }),
            )
        }

        setOpen = (open) => {
            open ? this.show() : this.close()
        }

        close = () => {
            updateStack((prevStack) =>
                prevStack.map((modal) => {
                    if (modal.id === this.id && modal.isOpen) {
                        Object.keys(modal.listeners).forEach((event) => {
                            modal.off(event)
                        })

                        modal.isOpen = false
                        modal.onCloseCallback?.()
                    }
                    return modal
                }),
            )
        }

        afterLeave = () => {
            if (this.isOpen) {
                return
            }

            updateStack((prevStack) => {
                const updatedStack = prevStack.map((modal) => {
                    if (modal.id === this.id && !modal.isOpen) {
                        modal.shouldRender = false
                        modal.afterLeaveCallback?.()
                        modal.afterLeaveCallback = null
                    }
                    return modal
                })

                return this.index === 0 ? [] : updatedStack
            })
        }

        on = (event, callback) => {
            this.listeners[event] = this.listeners[event] ?? []
            this.listeners[event].push(callback)
        }

        off = (event, callback) => {
            if (callback) {
                this.listeners[event] = this.listeners[event]?.filter((cb) => cb !== callback) ?? []
            } else {
                delete this.listeners[event]
            }
        }

        emit = (event, ...args) => {
            this.listeners[event]?.forEach((callback) => callback(...args))
        }

        registerEventListenersFromProps = (props) => {
            const unsubscribers = []

            Object.keys(props)
                .filter((key) => key.startsWith('on'))
                .forEach((key) => {
                    // e.g. onRefreshKey -> refresh-key
                    const snakeCaseKey = key
                        .replace(/^on/, '')
                        .replace(/^./, (firstLetter) => firstLetter.toLowerCase())
                        .replace(/([A-Z])/g, '-$1')
                        .toLowerCase()

                    this.on(snakeCaseKey, props[key])
                    unsubscribers.push(() => this.off(snakeCaseKey, props[key]))
                })

            return () => unsubscribers.forEach((unsub) => unsub())
        }

        reload = (options = {}) => {
            let keys = Object.keys(this.response.props)

            if (options.only) {
                keys = only(keys, options.only)
            }

            if (options.except) {
                keys = except(keys, options.except)
            }

            if (!this.response?.url) {
                return
            }

            Axios.get(this.response.url, {
                headers: {
                    Accept: 'text/html, application/xhtml+xml',
                    'X-Inertia': true,
                    'X-Inertia-Partial-Component': this.response.component,
                    'X-Inertia-Version': this.response.version,
                    'X-Inertia-Partial-Data': keys.join(','),
                    'X-InertiaUI-Modal': true,
                    'X-InertiaUI-Modal-Use-Router': 0,
                },
            }).then((response) => {
                this.updateProps(response.data.props)
            })
        }

        updateProps = (props) => {
            Object.assign(this.props, props)
            updateStack((prevStack) => prevStack) // Trigger re-render
        }
    }

    const pushFromResponseData = (responseData, config = {}, onClose = null, onAfterLeave = null) => {
        return resolveComponent(responseData.component).then((component) => push(component, responseData, config, onClose, onAfterLeave))
    }

    const push = (component, response, config, onClose, afterLeave) => {
        const newModal = new Modal(component, response, config, onClose, afterLeave)
        newModal.index = stack.length

        updateStack((prevStack) => [...prevStack, newModal])

        newModal.show()

        return newModal
    }

    function pushLocalModal(name, config, onClose, afterLeave) {
        if (!localModals[name]) {
            throw new Error(`The local modal "${name}" has not been registered.`)
        }

        const modal = push(null, {}, config, onClose, afterLeave)
        modal.name = name
        localModals[name].callback(modal)
        return modal
    }

    const visitModal = (url, options = {}) =>
        visit(
            url,
            options.method ?? 'get',
            options.data ?? {},
            options.headers ?? {},
            options.config ?? {},
            options.onClose,
            options.onAfterLeave,
            options.queryStringArrayFormat ?? 'brackets',
            options.navigate ?? getConfig('navigate'),
        )

    const visit = (
        href,
        method,
        payload = {},
        headers = {},
        config = {},
        onClose = null,
        onAfterLeave = null,
        queryStringArrayFormat = 'brackets',
        useBrowserHistory = false,
    ) => {
        return new Promise((resolve, reject) => {
            if (href.startsWith('#')) {
                resolve(pushLocalModal(href.substring(1), config, onClose, onAfterLeave))
                return
            }

            const [url, data] = mergeDataIntoQueryString(method, href || '', payload, queryStringArrayFormat)

            let useInertiaRouter = useBrowserHistory && stack.length === 0

            if (stack.length === 0) {
                baseUrl = typeof window !== 'undefined' ? window.location.href : ''
            }

            headers = {
                ...headers,
                Accept: 'text/html, application/xhtml+xml',
                'X-Requested-With': 'XMLHttpRequest',
                'X-Inertia': true,
                'X-Inertia-Version': pageVersion,
                'X-InertiaUI-Modal': true,
                'X-InertiaUI-Modal-Use-Router': useInertiaRouter ? 1 : 0,
            }

            if (useInertiaRouter) {
                newModalOnBase = null
                // Pushing the modal to the stack will be handled by the ModalRoot...
                return router.visit(url, {
                    method,
                    data,
                    headers,
                    preserveScroll: true,
                    preserveState: true,
                    onError: reject,
                    onFinish: () => {
                        waitFor(() => newModalOnBase).then((modal) => {
                            const originalOnClose = modal.onCloseCallback
                            const originalAfterLeave = modal.afterLeaveCallback

                            modal.update(
                                config,
                                () => {
                                    onClose?.()
                                    originalOnClose?.()
                                },
                                () => {
                                    onAfterLeave?.()
                                    originalAfterLeave?.()
                                },
                            )

                            resolve(modal)
                        })
                    },
                })
            }

            //

            Axios({
                url,
                method,
                data,
                headers,
            })
                .then((response) => resolve(pushFromResponseData(response.data, config, onClose, onAfterLeave)))
                .catch((error) => {
                    reject(error)
                })
        })
    }

    const registerLocalModal = (name, callback) => {
        setLocalModals((prevLocalModals) => ({
            ...prevLocalModals,
            [name]: { name, callback },
        }))
    }

    const removeLocalModal = (name) => {
        setLocalModals((prevLocalModals) => {
            const newLocalModals = { ...prevLocalModals }
            delete newLocalModals[name]
            return newLocalModals
        })
    }

    const value = {
        stack,
        localModals,
        push,
        pushFromResponseData,
        closeAll: () => {
            localStackCopy.reverse().forEach((modal) => modal.close())
        },
        reset: () => updateStack(() => []),
        visit,
        visitModal,
        registerLocalModal,
        removeLocalModal,
    }

    return <ModalStackContext.Provider value={value}>{children}</ModalStackContext.Provider>
}

export const useModalStack = () => {
    const context = useContext(ModalStackContext)
    if (context === null) {
        throw new Error('useModalStack must be used within a ModalStackProvider')
    }
    return context
}

export const modalPropNames = ['closeButton', 'closeExplicitly', 'maxWidth', 'paddingClasses', 'panelClasses', 'position', 'slideover']

export const renderApp = (App, pageProps) => {
    if (pageProps.initialPage) {
        pageVersion = pageProps.initialPage.version
    }

    if (pageProps.resolveComponent) {
        resolveComponent = pageProps.resolveComponent
    }

    const renderInertiaApp = ({ Component, props, key }) => {
        const renderComponent = () => {
            const child = createElement(Component, { key, ...props })

            if (typeof Component.layout === 'function') {
                return Component.layout(child)
            }

            if (Array.isArray(Component.layout)) {
                const layouts = Component.layout
                    .concat(child)
                    .reverse()
                    .reduce((children, Layout) => createElement(Layout, props, children))

                return layouts
            }

            return child
        }

        return (
            <>
                {renderComponent()}
                <ModalRoot />
            </>
        )
    }

    return (
        <ModalStackProvider>
            <App {...pageProps}>{renderInertiaApp}</App>
        </ModalStackProvider>
    )
}

export const ModalRoot = ({ children }) => {
    const context = useContext(ModalStackContext)

    let isNavigating = false
    let previousModalOnBase = false

    useEffect(() => router.on('start', () => (isNavigating = true)), [])
    useEffect(() => router.on('finish', () => (isNavigating = false)), [])
    useEffect(
        () =>
            router.on('navigate', function ($event) {
                const modalOnBase = $event.detail.page.props._inertiaui_modal

                if (!modalOnBase) {
                    previousModalOnBase && context.closeAll()
                    return
                }

                previousModalOnBase = modalOnBase
                baseUrl = modalOnBase.baseUrl

                context
                    .pushFromResponseData(modalOnBase, {}, () => {
                        if (!modalOnBase.baseUrl) {
                            console.error('No base url in modal response data so cannot navigate back')
                            return
                        }
                        if (!isNavigating && window.location.href !== modalOnBase.baseUrl) {
                            router.visit(modalOnBase.baseUrl, {
                                preserveScroll: true,
                                preserveState: true,
                            })
                        }
                    })
                    .then((newModal) => {
                        newModalOnBase = newModal
                    })
            }),
        [],
    )

    const axiosRequestInterceptor = (config) => {
        // A Modal is opened on top of a base route, so we need to pass this base route
        // so it can redirect back with the back() helper method...
        config.headers['X-InertiaUI-Modal-Base-Url'] = baseUrl
        return config
    }

    useEffect(() => {
        Axios.interceptors.request.use(axiosRequestInterceptor)
        return () => Axios.interceptors.request.eject(axiosRequestInterceptor)
    }, [])

    const $page = usePage()

    useEffect(() => {
        const newModal = $page.props?._inertiaui_modal
        const previousModal = newModalOnBase?.response

        if (newModal && previousModal && newModal.component === previousModal.component && newModal.url === previousModal.url) {
            context.stack[0].updateProps(newModal.props ?? {})
        }
    }, [$page.props?._inertiaui_modal])

    return (
        <>
            {children}
            {context.stack.length > 0 && <ModalRenderer index={0} />}
        </>
    )
}
