// svelte/src/lib/ModalLink.svelte
<script>
    import { modalPropNames, useModalStack } from './modalStack.svelte.js'
    import { only, rejectNullValues } from './helpers.js'
    import { getConfig } from './config.js'
    import { setContext, onDestroy } from 'svelte'

    let {
        href,
        method = 'get',
        data = {},
        as = 'a',
        headers = {},
        queryStringArrayFormat = 'brackets',
        navigate = null,
        onAfterLeave = null,
        onBlur = null,
        onClose = null,
        onError = null,
        onFocus = null,
        onStart = null,
        onSuccess = null,
        // Modal configuration props (passthrough to Modal)
        closeButton = null,
        closeExplicitly = null,
        maxWidth = null,
        paddingClasses = null,
        panelClasses = null,
        position = null,
        slideover = null,
        children,
        ...restProps
    } = $props()

    let loading = $state(false)
    let modalStack = useModalStack()
    let modalContext = $state(null)
    let isBlurred = false
    let shouldNavigate = $derived(navigate ?? getConfig('navigate'))
    let unsubscribeEventListeners = null

    $effect(() => setContext('modalContext', modalContext))

    $effect(() => {
        if (modalContext) {
            if (modalContext.onTopOfStack && isBlurred) {
                onFocus?.()
            } else if (!modalContext.onTopOfStack && !isBlurred) {
                onBlur?.()
            }

            isBlurred = !modalContext.onTopOfStack
        }
    })

    function handleClose() {
        onClose?.()
    }

    function handleAfterLeave() {
        modalContext = null
        onAfterLeave?.()
    }

    function registerEventListeners() {
        if (modalContext) {
            unsubscribeEventListeners = modalContext.registerEventListenersFromProps(restProps)
        }
    }

    async function handle(e) {
        e?.preventDefault()
        if (loading) return

        if (!href.startsWith('#')) {
            loading = true
            onStart?.()
        }

        try {
            const props = {
                closeButton,
                closeExplicitly,
                maxWidth,
                paddingClasses,
                panelClasses,
                position,
                slideover,
                ...restProps,
            }

            const newModalContext = await modalStack.visit(
                href,
                method,
                data,
                headers,
                rejectNullValues(only(props, modalPropNames)),
                handleClose,
                handleAfterLeave,
                queryStringArrayFormat,
                shouldNavigate,
            )

            modalContext = newModalContext
            registerEventListeners()
            onSuccess?.()
        } catch (error) {
            onError?.(error)
        } finally {
            loading = false
        }
    }

    onDestroy(() => {
        unsubscribeEventListeners?.()
    })

    let componentProps = $derived.by(() => {
        const filtered = {}
        Object.keys(restProps).forEach((key) => {
            if (modalPropNames.includes(key)) return
            if (key.startsWith('on') && typeof restProps[key] === 'function') return
            if (['href', 'method', 'data', 'as', 'headers', 'queryStringArrayFormat', 'navigate'].includes(key)) return

            filtered[key] = restProps[key]
        })
        return filtered
    })
</script>

<svelte:element
    this={as}
    {href}
    {...componentProps}
    onclick={handle}
>
    {@render children?.({ loading })}
</svelte:element>

// react/src/ModalLink.jsx
import { useCallback, useState, useEffect, useMemo } from 'react'
import { useModalStack, modalPropNames } from './ModalRoot'
import { only, rejectNullValues, isStandardDomEvent } from './helpers'
import { getConfig } from './config'

const ModalLink = ({
    href,
    method = 'get',
    data = {},
    as: Component = 'a',
    headers = {},
    queryStringArrayFormat = 'brackets',
    onAfterLeave = null,
    onBlur = null,
    onClose = null,
    onError = null,
    onFocus = null,
    onStart = null,
    onSuccess = null,
    navigate = null,
    children,
    ...props
}) => {
    const [loading, setLoading] = useState(false)
    const [modalContext, setModalContext] = useState(null)
    const { stack, visit } = useModalStack()

    const shouldNavigate = useMemo(() => {
        return navigate ?? getConfig('navigate')
    }, [navigate])

    // Separate standard props from custom event handlers
    const standardProps = {}
    const customEvents = {}

    Object.keys(props).forEach((key) => {
        if (modalPropNames.includes(key)) {
            return
        }

        if (key.startsWith('on') && typeof props[key] === 'function') {
            if (isStandardDomEvent(key)) {
                standardProps[key] = props[key]
            } else {
                customEvents[key] = props[key]
            }
        } else {
            standardProps[key] = props[key]
        }
    })

    const [isBlurred, setIsBlurred] = useState(false)

    useEffect(() => {
        if (!modalContext) {
            return
        }

        if (modalContext.onTopOfStack && isBlurred) {
            onFocus?.()
        } else if (!modalContext.onTopOfStack && !isBlurred) {
            onBlur?.()
        }

        setIsBlurred(!modalContext.onTopOfStack)
    }, [stack])

    const onCloseCallback = useCallback(() => {
        onClose?.()
    }, [onClose])

    const onAfterLeaveCallback = useCallback(() => {
        setModalContext(null)
        onAfterLeave?.()
    }, [onAfterLeave])

    const handle = useCallback(
        (e) => {
            e?.preventDefault()
            if (loading) return

            if (!href.startsWith('#')) {
                setLoading(true)
                onStart?.()
            }

            visit(
                href,
                method,
                data,
                headers,
                rejectNullValues(only(props, modalPropNames)),
                () => onCloseCallback(stack.length),
                onAfterLeaveCallback,
                queryStringArrayFormat,
                shouldNavigate,
            )
                .then((newModalContext) => {
                    setModalContext(newModalContext)
                    newModalContext.registerEventListenersFromProps(customEvents)
                    onSuccess?.()
                })
                .catch((error) => {
                    console.error(error)
                    onError?.(error)
                })
                .finally(() => setLoading(false))
        },
        [href, method, data, headers, queryStringArrayFormat, props, onCloseCallback, onAfterLeaveCallback],
    )

    return (
        <Component
            {...standardProps}
            href={href}
            onClick={handle}
        >
            {typeof children === 'function' ? children({ loading }) : children}
        </Component>
    )
}

export default ModalLink
