// vue/src/Modal.vue
<script setup>
import ModalContent from './ModalContent.vue'
import HeadlessModal from './HeadlessModal.vue'
import SlideoverContent from './SlideoverContent.vue'
import { ref, watch, onBeforeUnmount } from 'vue'
import { modalDOMHandler } from './helpers'

const modal = ref(null)
const rendered = ref(false)
const preparedDOM = ref(false)

defineEmits(['after-leave', 'blur', 'close', 'focus', 'success'])

watch(
    () => modal.value,
    (value) => {
        if (value?.index === 0) {
            modalDOMHandler.prepare()
            preparedDOM.value = true
        }
    },
)

onBeforeUnmount(() => {
    if (preparedDOM.value) {
        modalDOMHandler.cleanup()
    }
})

defineExpose({
    afterLeave: () => modal.value?.afterLeave(),
    close: () => modal.value?.close(),
    emit: (...args) => modal.value?.emit(...args),
    getChildModal: () => modal.value?.getChildModal(),
    getParentModal: () => modal.value?.getParentModal(),
    reload: (...args) => modal.value?.reload(...args),
    setOpen: (...args) => modal.value?.setOpen(...args),

    get config() {
        return modal.value?.config
    },
    get id() {
        return modal.value?.id
    },
    get index() {
        return modal.value?.index
    },
    get isOpen() {
        return modal.value?.isOpen
    },
    get modalContext() {
        return modal.value?.modalContext
    },
    get onTopOfStack() {
        return modal.value?.onTopOfStack
    },
    get shouldRender() {
        return modal.value?.shouldRender
    },
})
</script>

<template>
    <HeadlessModal
        ref="modal"
        v-slot="{
            afterLeave,
            close,
            config,
            emit,
            getChildModal,
            getParentModal,
            id,
            index,
            isOpen,
            modalContext,
            onTopOfStack,
            reload,
            setOpen,
            shouldRender,
        }"
        @success="$emit('success')"
        @close="$emit('close')"
        @focus="$emit('focus')"
        @blur="$emit('blur')"
    >
        <teleport
            v-if="shouldRender"
            to="body"
        >
            <div
                :data-inertiaui-modal-id="id"
                :data-inertiaui-modal-index="index"
                class="im-dialog relative z-20"
                :aria-hidden="!onTopOfStack"
            >
                <Transition
                    v-if="index === 0 && onTopOfStack"
                    :appear="!rendered"
                    enter-active-class="transition transform ease-in-out duration-300"
                    enter-from-class="opacity-0"
                    enter-to-class="opacity-100"
                    leave-active-class="transition transform ease-in-out duration-300"
                    leave-from-class="opacity-100"
                    leave-to-class="opacity-0"
                    @after-appear="rendered = true"
                    @after-leave="$emit('after-leave')"
                >
                    <div
                        v-show="isOpen"
                        class="im-backdrop fixed inset-0 z-30 bg-black/75"
                    />
                </Transition>

                <!-- On multiple modals, only show a backdrop for the modal that is on top of the stack -->
                <div
                    v-if="index > 0 && onTopOfStack"
                    class="im-backdrop fixed inset-0 z-30 bg-black/75"
                />

                <!-- The modal/slideover content itself -->
                <component
                    :is="config?.slideover ? SlideoverContent : ModalContent"
                    :modal-context="modalContext"
                    :config="config"
                >
                    <slot
                        :id="id"
                        :after-leave="afterLeave"
                        :close="close"
                        :config="config"
                        :emit="emit"
                        :get-child-modal="getChildModal"
                        :get-parent-modal="getParentModal"
                        :index="index"
                        :is-open="isOpen"
                        :modal-context="modalContext"
                        :on-top-of-stack="onTopOfStack"
                        :reload="reload"
                        :set-open="setOpen"
                        :should-render="shouldRender"
                    />
                </component>
            </div>
        </teleport>
    </HeadlessModal>
</template>

// react/src/Modal.jsx
import { Transition, TransitionChild } from '@headlessui/react'
import { forwardRef, useRef, useImperativeHandle, useEffect } from 'react'
import HeadlessModal from './HeadlessModal'
import ModalContent from './ModalContent'
import SlideoverContent from './SlideoverContent'
import { modalDOMHandler } from './helpers'

const Modal = forwardRef(({ name, children, ...props }, ref) => {
    const renderChildren = (contentProps) => {
        if (typeof children === 'function') {
            return children(contentProps)
        }

        return children
    }

    const headlessModalRef = useRef(null)

    useEffect(() => {
        if (headlessModalRef?.current?.index === 0) {
            modalDOMHandler.prepare()

            return () => modalDOMHandler.cleanup()
        }
    }, [headlessModalRef])

    useImperativeHandle(ref, () => headlessModalRef.current, [headlessModalRef])

    return (
        <HeadlessModal
            ref={headlessModalRef}
            name={name}
            {...props}
        >
            {({
                afterLeave,
                close,
                config,
                emit,
                getChildModal,
                getParentModal,
                id,
                index,
                isOpen,
                modalContext,
                onTopOfStack,
                reload,
                setOpen,
                shouldRender,
            }) => (
                <Transition
                    appear={true}
                    show={isOpen ?? false}
                >
                    <div
                        className="im-dialog relative z-20"
                        data-inertiaui-modal-id={id}
                        data-inertiaui-modal-index={index}
                    >
                        {/* Only transition the backdrop for the first modal in the stack */}
                        {index === 0 ? (
                            <TransitionChild
                                enter="transition transform ease-in-out duration-300"
                                enterFrom="opacity-0"
                                enterTo="opacity-100"
                                leave="transition transform ease-in-out duration-300"
                                leaveFrom="opacity-100"
                                leaveTo="opacity-0"
                            >
                                {onTopOfStack ? (
                                    <div
                                        className="im-backdrop fixed inset-0 z-30 bg-black/75"
                                        aria-hidden="true"
                                    />
                                ) : (
                                    <div />
                                )}
                            </TransitionChild>
                        ) : null}

                        {/* On multiple modals, only show a backdrop for the modal that is on top of the stack */}
                        {index > 0 && onTopOfStack ? <div className="im-backdrop fixed inset-0 z-30 bg-black/75" /> : null}

                        {/* The modal/slideover content itself */}
                        {config.slideover ? (
                            <SlideoverContent
                                modalContext={modalContext}
                                config={config}
                            >
                                {renderChildren({
                                    afterLeave,
                                    close,
                                    config,
                                    emit,
                                    getChildModal,
                                    getParentModal,
                                    id,
                                    index,
                                    isOpen,
                                    modalContext,
                                    onTopOfStack,
                                    reload,
                                    setOpen,
                                    shouldRender,
                                })}
                            </SlideoverContent>
                        ) : (
                            <ModalContent
                                modalContext={modalContext}
                                config={config}
                            >
                                {renderChildren({
                                    afterLeave,
                                    close,
                                    config,
                                    emit,
                                    getChildModal,
                                    getParentModal,
                                    id,
                                    index,
                                    isOpen,
                                    modalContext,
                                    onTopOfStack,
                                    reload,
                                    setOpen,
                                    shouldRender,
                                })}
                            </ModalContent>
                        )}
                    </div>
                </Transition>
            )}
        </HeadlessModal>
    )
})

Modal.displayName = 'Modal'
export default Modal
