// vue/src/WhenVisible.vue
<script setup lang="ts">
// See: https://github.com/inertiajs/inertia/blob/48bcd21fb7daf467d0df1bfde2408f161f94a579/packages/vue3/src/whenVisible.ts
import { ref, onMounted, onUnmounted, inject } from 'vue'
import type { ModalInstance } from './types'

interface WhenVisibleProps {
    data?: string | string[]
    params?: Record<string, any>
    buffer?: number
    as?: string
    always?: boolean
}

const props = withDefaults(defineProps<WhenVisibleProps>(), {
    buffer: 0,
    as: 'div',
    always: false,
})

const modalContext = inject<ModalInstance | null>('modalContext')

if (!modalContext) {
    throw new Error('Deferred component must be used inside a Modal component')
}

const loaded = ref(false)
const fetching = ref(false)
const rootElement = ref(null)
let observer = null

const getReloadParams = () => {
    if (props.data) {
        return { only: Array.isArray(props.data) ? props.data : [props.data] }
    }

    if (!props.params) {
        throw new Error('You must provide either a `data` or `params` prop.')
    }

    return props.params
}

const observeElement = () => {
    if (!rootElement.value) {
        return
    }

    observer = new IntersectionObserver(
        (entries) => {
            if (!entries[0].isIntersecting) {
                return
            }

            if (!props.always) {
                observer.disconnect()
            }

            if (fetching.value) {
                return
            }

            fetching.value = true
            const reloadParams = getReloadParams()

            modalContext?.reload({
                ...reloadParams,
                onStart: () => {
                    fetching.value = true
                    reloadParams.onStart?.()
                },
                onFinish: () => {
                    loaded.value = true
                    fetching.value = false
                    reloadParams.onFinish?.()
                },
            })
        },
        { rootMargin: `${props.buffer}px` },
    )

    observer.observe(rootElement.value)
}

onMounted(observeElement)
onUnmounted(() => observer?.disconnect())
</script>

<template>
    <component
        :is="props.as"
        ref="rootElement"
    >
        <slot v-if="loaded"></slot>
        <slot
            v-else
            name="fallback"
        ></slot>
    </component>
</template>

// react/src/WhenVisible.tsx
// See: https://github.com/inertiajs/inertia/blob/48bcd21fb7daf467d0df1bfde2408f161f94a579/packages/react/src/WhenVisible.ts
import { createElement, useCallback, useEffect, useRef, useState, ReactNode, ElementType } from 'react'

import type { ReloadOptions } from './types'
import useModal from './useModal'

interface WhenVisibleProps {
    children: ReactNode
    data?: string | string[]
    params?: ReloadOptions
    buffer?: number
    as?: ElementType
    always?: boolean
    fallback?: ReactNode
}

const WhenVisible = ({ children, data, params, buffer, as, always, fallback }: WhenVisibleProps) => {
    always = always ?? false
    as = as ?? 'div'
    fallback = fallback ?? null

    const [loaded, setLoaded] = useState(false)
    const hasFetched = useRef(false)
    const fetching = useRef(false)
    const ref = useRef<HTMLElement>(null)

    const modal = useModal()

    const getReloadParams = useCallback((): ReloadOptions => {
        if (data) {
            return {
                only: Array.isArray(data) ? data : [data],
            }
        }

        if (!params) {
            throw new Error('You must provide either a `data` or `params` prop.')
        }

        return params
    }, [params, data])

    useEffect(() => {
        if (!ref.current) {
            return
        }

        const observer = new IntersectionObserver(
            (entries) => {
                if (!entries[0].isIntersecting) {
                    return
                }

                if (!always && hasFetched.current) {
                    observer.disconnect()
                }

                if (fetching.current) {
                    return
                }

                hasFetched.current = true
                fetching.current = true

                const reloadParams = getReloadParams()

                modal?.reload({
                    ...reloadParams,
                    onStart: () => {
                        fetching.current = true
                        reloadParams.onStart?.()
                    },
                    onFinish: () => {
                        setLoaded(true)
                        fetching.current = false
                        reloadParams.onFinish?.()

                        if (!always) {
                            observer.disconnect()
                        }
                    },
                })
            },
            {
                rootMargin: `${buffer || 0}px`,
            },
        )

        observer.observe(ref.current)

        return () => {
            observer.disconnect()
        }
    }, [ref, getReloadParams, buffer])

    if (always || !loaded) {
        return createElement(
            as,
            {
                props: null,
                ref,
            },
            loaded ? children : fallback,
        )
    }

    return loaded ? children : null
}

WhenVisible.displayName = 'InertiaWhenVisible'

export default WhenVisible
