// svelte/src/lib/WhenVisible.svelte
<script>
    // See: https://github.com/inertiajs/inertia/blob/master/packages/svelte/src/components/WhenVisible.svelte
    import { onMount, onDestroy, getContext } from 'svelte'

    let { data = null, params = null, buffer = 0, as = 'div', always = false, children, fallback } = $props()

    const modalContext = getContext('modalContext')

    if (!modalContext) {
        throw new Error('WhenVisible component must be used inside a Modal component')
    }

    let loaded = $state(false)
    let fetching = $state(false)
    let rootElement = $state(null)
    let observer = null

    function getReloadParams() {
        if (data) {
            return { only: Array.isArray(data) ? data : [data] }
        }

        if (!params) {
            throw new Error('You must provide either a `data` or `params` prop.')
        }

        return params
    }

    function observeElement() {
        if (!rootElement) {
            return
        }

        observer = new IntersectionObserver(
            (entries) => {
                if (!entries[0].isIntersecting) {
                    return
                }

                if (!always) {
                    observer.disconnect()
                }

                if (fetching) {
                    return
                }

                fetching = true
                const reloadParams = getReloadParams()

                modalContext.reload({
                    ...reloadParams,
                    onStart: () => {
                        fetching = true
                        reloadParams.onStart?.()
                    },
                    onFinish: () => {
                        loaded = true
                        fetching = false
                        reloadParams.onFinish?.()
                    },
                })
            },
            { rootMargin: `${buffer}px` },
        )

        observer.observe(rootElement)
    }

    onMount(() => {
        observeElement()
    })

    onDestroy(() => {
        observer?.disconnect()
    })
</script>

<svelte:element
    this={as}
    bind:this={rootElement}
>
    {#if loaded}
        {@render children?.()}
    {:else}
        {@render fallback?.()}
    {/if}
</svelte:element>

// react/src/WhenVisible.jsx
// See: https://github.com/inertiajs/inertia/blob/48bcd21fb7daf467d0df1bfde2408f161f94a579/packages/react/src/WhenVisible.ts
import { createElement, useCallback, useEffect, useRef, useState } from 'react'
import useModal from './useModal'

const WhenVisible = ({ children, data, params, buffer, as, always, fallback }) => {
    always = always ?? false
    as = as ?? 'div'
    fallback = fallback ?? null

    const [loaded, setLoaded] = useState(false)
    const hasFetched = useRef(false)
    const fetching = useRef(false)
    const ref = useRef(null)

    const modal = useModal()

    const getReloadParams = useCallback(() => {
        if (data) {
            return {
                only: Array.isArray(data) ? data : [data],
            }
        }

        if (!params) {
            throw new Error('You must provide either a `data` or `params` prop.')
        }

        return params
    }, [params, data])

    useEffect(() => {
        if (!ref.current) {
            return
        }

        const observer = new IntersectionObserver(
            (entries) => {
                if (!entries[0].isIntersecting) {
                    return
                }

                if (!always && hasFetched.current) {
                    observer.disconnect()
                }

                if (fetching.current) {
                    return
                }

                hasFetched.current = true
                fetching.current = true

                const reloadParams = getReloadParams()

                modal.reload({
                    ...reloadParams,
                    onStart: (e) => {
                        fetching.current = true
                        reloadParams.onStart?.(e)
                    },
                    onFinish: (e) => {
                        setLoaded(true)
                        fetching.current = false
                        reloadParams.onFinish?.(e)

                        if (!always) {
                            observer.disconnect()
                        }
                    },
                })
            },
            {
                rootMargin: `${buffer || 0}px`,
            },
        )

        observer.observe(ref.current)

        return () => {
            observer.disconnect()
        }
    }, [ref, getReloadParams, buffer])

    if (always || !loaded) {
        return createElement(
            as,
            {
                props: null,
                ref,
            },
            loaded ? children : fallback,
        )
    }

    return loaded ? children : null
}

WhenVisible.displayName = 'InertiaWhenVisible'

export default WhenVisible
