// react/src/ModalLink.tsx
import { useCallback, useState, useEffect, useMemo, useRef, ReactNode, ElementType, MouseEvent } from 'react'
import { useModalStack, modalPropNames, prefetch as prefetchModal } from './ModalRoot'
import { only, rejectNullValues, isStandardDomEvent, shouldInterceptClick } from './helpers'
import { getConfig } from './config'
import type { Modal, PrefetchOption, HttpMethod } from './types'
import type { RequestPayload } from '@inertiajs/core'

interface ModalLinkProps {
    href: string
    method?: HttpMethod
    data?: RequestPayload
    as?: ElementType
    headers?: Record<string, string>
    queryStringArrayFormat?: 'brackets' | 'indices'
    onAfterLeave?: () => void
    onBlur?: () => void
    onClose?: () => void
    onError?: (error: unknown) => void
    onFocus?: () => void
    onStart?: () => void
    onSuccess?: () => void
    onPrefetching?: () => void
    onPrefetched?: () => void
    navigate?: boolean
    // Prefetch options (#146)
    prefetch?: PrefetchOption
    cacheFor?: number
    children: ReactNode | ((props: { loading: boolean }) => ReactNode)
    [key: string]: unknown
}

const ModalLink = ({
    href,
    method = 'get',
    data = {} as RequestPayload,
    as: Component = 'a',
    headers = {},
    queryStringArrayFormat = 'brackets' as const,
    onAfterLeave,
    onBlur,
    onClose,
    onError,
    onFocus,
    onStart,
    onSuccess,
    onPrefetching,
    onPrefetched,
    navigate,
    prefetch = false,
    cacheFor = 30000,
    children,
    ...props
}: ModalLinkProps) => {
    const [loading, setLoading] = useState(false)
    const [modalContext, setModalContext] = useState<Modal | null>(null)
    const { stack, visit } = useModalStack()
    const hoverTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)

    const shouldNavigate = useMemo(() => {
        return navigate ?? (getConfig('navigate') as boolean)
    }, [navigate])

    // Prefetch logic (#146)
    const prefetchModes = useMemo(() => {
        if (prefetch === true) {
            return ['hover']
        }
        if (prefetch === false) {
            return []
        }
        if (Array.isArray(prefetch)) {
            return prefetch
        }
        return [prefetch]
    }, [prefetch])

    const doPrefetch = useCallback(() => {
        prefetchModal(href, {
            method,
            data,
            headers,
            queryStringArrayFormat,
            cacheFor,
            onPrefetching: onPrefetching ?? undefined,
            onPrefetched: onPrefetched ?? undefined,
        })
    }, [href, method, data, headers, queryStringArrayFormat, cacheFor, onPrefetching, onPrefetched])

    const handleMouseEnter = useCallback(() => {
        if (!prefetchModes.includes('hover')) return

        hoverTimeout.current = setTimeout(() => {
            doPrefetch()
        }, 75) // Small delay to avoid prefetching on accidental hovers
    }, [prefetchModes, doPrefetch])

    const handleMouseLeave = useCallback(() => {
        if (hoverTimeout.current) {
            clearTimeout(hoverTimeout.current)
            hoverTimeout.current = null
        }
    }, [])

    const handleMouseDown = useCallback(
        (event: MouseEvent) => {
            if (!prefetchModes.includes('click')) return
            if (event.button !== 0) return // Only left click

            doPrefetch()
        },
        [prefetchModes, doPrefetch],
    )

    // Prefetch on mount
    useEffect(() => {
        if (prefetchModes.includes('mount')) {
            doPrefetch()
        }
    }, [])

    // Cleanup hover timeout on unmount
    useEffect(() => {
        return () => {
            if (hoverTimeout.current) {
                clearTimeout(hoverTimeout.current)
            }
        }
    }, [])

    // Separate standard props from custom event handlers
    const standardProps: Record<string, unknown> = {}
    const customEvents: Record<string, (...args: unknown[]) => void> = {}

    Object.keys(props).forEach((key) => {
        if (modalPropNames.includes(key)) {
            return
        }

        if (key.startsWith('on') && typeof props[key] === 'function') {
            if (isStandardDomEvent(key)) {
                standardProps[key] = props[key]
            } else {
                customEvents[key] = props[key] as (...args: unknown[]) => void
            }
        } else {
            standardProps[key] = props[key]
        }
    })

    const [isBlurred, setIsBlurred] = useState(false)

    useEffect(() => {
        if (!modalContext) {
            return
        }

        if (modalContext.onTopOfStack && isBlurred) {
            onFocus?.()
        } else if (!modalContext.onTopOfStack && !isBlurred) {
            onBlur?.()
        }

        setIsBlurred(!modalContext.onTopOfStack)
    }, [stack])

    const onCloseCallback = useCallback(() => {
        onClose?.()
    }, [onClose])

    const onAfterLeaveCallback = useCallback(() => {
        setModalContext(null)
        onAfterLeave?.()
    }, [onAfterLeave])

    const handle = useCallback(
        (e?: MouseEvent) => {
            if (!shouldInterceptClick(e, Component === 'a')) {
                return
            }
            e?.preventDefault()
            if (loading) return

            if (!href.startsWith('#')) {
                setLoading(true)
                onStart?.()
            }

            visit(
                href,
                method,
                data,
                headers,
                rejectNullValues(only(props, modalPropNames)) as Record<string, unknown>,
                () => onCloseCallback(),
                onAfterLeaveCallback,
                queryStringArrayFormat,
                shouldNavigate,
            )
                .then((newModalContext) => {
                    setModalContext(newModalContext)
                    newModalContext.registerEventListenersFromProps(customEvents)
                    onSuccess?.()
                })
                .catch((error) => {
                    console.error(error)
                    onError?.(error)
                })
                .finally(() => setLoading(false))
        },
        [href, method, data, headers, queryStringArrayFormat, props, onCloseCallback, onAfterLeaveCallback, Component],
    )

    return (
        <Component
            {...standardProps}
            href={href}
            onClick={handle}
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
            onMouseDown={handleMouseDown}
        >
            {typeof children === 'function' ? children({ loading }) : children}
        </Component>
    )
}

export default ModalLink

// vue/src/ModalLink.vue
<script setup>
import { modalPropNames, useModalStack, prefetch as prefetchModal } from './modalStack'
import { ref, provide, computed, watch, useAttrs, onBeforeUnmount, onMounted } from 'vue'
import { only, rejectNullValues, shouldInterceptClick } from './helpers'
import { getConfig } from './config'

const props = defineProps({
    href: {
        type: String,
        required: true,
    },
    method: {
        type: String,
        default: 'get',
    },
    data: {
        type: Object,
        default: () => ({}),
    },
    as: {
        type: [String, Object],
        default: 'a',
    },
    headers: {
        type: Object,
        default: () => ({}),
    },
    queryStringArrayFormat: {
        type: String,
        default: 'brackets',
    },
    navigate: {
        type: Boolean,
        default: null,
    },
    // Prefetch options (#146)
    prefetch: {
        type: [Boolean, String, Array],
        default: false,
    },
    cacheFor: {
        type: Number,
        default: 30000,
    },
    // Passthrough to Modal.vue
    closeButton: {
        type: Boolean,
        required: false,
        default: null,
    },
    closeExplicitly: {
        type: Boolean,
        required: false,
        default: null,
    },
    closeOnClickOutside: {
        type: Boolean,
        required: false,
        default: null,
    },
    maxWidth: {
        type: String,
        required: false,
        default: null,
    },
    paddingClasses: {
        type: [Boolean, String],
        required: false,
        default: null,
    },
    panelClasses: {
        type: [Boolean, String],
        required: false,
        default: null,
    },
    position: {
        type: String,
        required: false,
        default: null,
    },
    slideover: {
        type: Boolean,
        required: false,
        default: null,
    },
})

const loading = ref(false)
const modalStack = useModalStack()
const modalContext = ref(null)

provide('modalContext', modalContext)

const emit = defineEmits(['after-leave', 'blur', 'close', 'error', 'focus', 'start', 'success', 'prefetching', 'prefetched'])
const isBlurred = ref(false)

const shouldNavigate = computed(() => {
    return props.navigate ?? getConfig('navigate')
})

// Prefetch logic (#146)
const hoverTimeout = ref(null)

const prefetchModes = computed(() => {
    if (props.prefetch === true) {
        return ['hover']
    }
    if (props.prefetch === false) {
        return []
    }
    if (Array.isArray(props.prefetch)) {
        return props.prefetch
    }
    return [props.prefetch]
})

function doPrefetch() {
    prefetchModal(props.href, {
        method: props.method,
        data: props.data,
        headers: props.headers,
        queryStringArrayFormat: props.queryStringArrayFormat,
        cacheFor: props.cacheFor,
        onPrefetching: () => emit('prefetching'),
        onPrefetched: () => emit('prefetched'),
    })
}

function onMouseenter() {
    if (!prefetchModes.value.includes('hover')) return

    hoverTimeout.value = setTimeout(() => {
        doPrefetch()
    }, 75) // Small delay to avoid prefetching on accidental hovers
}

function onMouseleave() {
    if (hoverTimeout.value) {
        clearTimeout(hoverTimeout.value)
        hoverTimeout.value = null
    }
}

function onMousedown(event) {
    if (!prefetchModes.value.includes('click')) return
    if (event.button !== 0) return // Only left click

    doPrefetch()
}

onMounted(() => {
    if (prefetchModes.value.includes('mount')) {
        doPrefetch()
    }
})

watch(
    () => modalContext.value?.onTopOfStack,
    (onTopOfStack) => {
        if (modalContext.value) {
            if (onTopOfStack && isBlurred.value) {
                emit('focus')
            } else if (!onTopOfStack) {
                emit('blur')
            }

            isBlurred.value = !onTopOfStack
        }
    },
)

const unsubscribeEventListeners = ref(null)

onBeforeUnmount(() => {
    unsubscribeEventListeners.value?.()
    if (hoverTimeout.value) {
        clearTimeout(hoverTimeout.value)
    }
})

const $attrs = useAttrs()

function registerEventListeners() {
    unsubscribeEventListeners.value = modalContext.value.registerEventListenersFromAttrs($attrs)
}

watch(modalContext, (value, oldValue) => {
    if (value && !oldValue) {
        registerEventListeners()
        emit('success')
    }
})

function onClose() {
    emit('close')
}

function onAfterLeave() {
    modalContext.value = null
    emit('after-leave')
}

function onClick(event) {
    if (!shouldInterceptClick(event, props.as === 'a')) {
        return
    }

    event.preventDefault()
    handle()
}

function handle() {
    if (loading.value) {
        return
    }

    if (!props.href.startsWith('#')) {
        loading.value = true
        emit('start')
    }

    modalStack
        .visit(
            props.href,
            props.method,
            props.data,
            props.headers,
            rejectNullValues(only(props, modalPropNames)),
            onClose,
            onAfterLeave,
            props.queryStringArrayFormat,
            shouldNavigate.value,
        )
        .then((context) => {
            modalContext.value = context
        })
        .catch((error) => {
            console.error(error)
            emit('error', error)
        })
        .finally(() => (loading.value = false))
}
</script>

<template>
    <component
        v-bind="$attrs"
        :is="as"
        :href="href"
        @click="onClick"
        @mouseenter="onMouseenter"
        @mouseleave="onMouseleave"
        @mousedown="onMousedown"
    >
        <slot :loading="loading" />
    </component>
</template>
