// svelte/src/lib/ModalLink.svelte
<script>
    import { modalPropNames, useModalStack } from './modalStack.svelte.js'
    import { only, rejectNullValues } from './helpers.js'
    import { getConfig } from './config.js'
    import { setContext, onDestroy } from 'svelte'

    let {
        href,
        method = 'get',
        data = {},
        as = 'a',
        headers = {},
        queryStringArrayFormat = 'brackets',
        navigate = null,
        onAfterLeave = null,
        onBlur = null,
        onClose = null,
        onError = null,
        onFocus = null,
        onStart = null,
        onSuccess = null,
        // Modal configuration props (passthrough to Modal)
        closeButton = null,
        closeExplicitly = null,
        maxWidth = null,
        paddingClasses = null,
        panelClasses = null,
        position = null,
        slideover = null,
        children,
        ...restProps
    } = $props()

    let loading = $state(false)
    let modalStack = useModalStack()
    let modalContext = $state(null)
    let isBlurred = false
    let shouldNavigate = $derived(navigate ?? getConfig('navigate'))
    let unsubscribeEventListeners = null

    $effect(() => setContext('modalContext', modalContext))

    $effect(() => {
        if (modalContext) {
            if (modalContext.onTopOfStack && isBlurred) {
                onFocus?.()
            } else if (!modalContext.onTopOfStack && !isBlurred) {
                onBlur?.()
            }

            isBlurred = !modalContext.onTopOfStack
        }
    })

    function handleClose() {
        onClose?.()
    }

    function handleAfterLeave() {
        modalContext = null
        onAfterLeave?.()
    }

    function registerEventListeners() {
        if (modalContext) {
            unsubscribeEventListeners = modalContext.registerEventListenersFromProps(restProps)
        }
    }

    async function handle(e) {
        e?.preventDefault()
        if (loading) return

        if (!href.startsWith('#')) {
            loading = true
            onStart?.()
        }

        try {
            const props = {
                closeButton,
                closeExplicitly,
                maxWidth,
                paddingClasses,
                panelClasses,
                position,
                slideover,
                ...restProps,
            }

            const newModalContext = await modalStack.visit(
                href,
                method,
                data,
                headers,
                rejectNullValues(only(props, modalPropNames)),
                handleClose,
                handleAfterLeave,
                queryStringArrayFormat,
                shouldNavigate,
            )

            modalContext = newModalContext
            registerEventListeners()
            onSuccess?.()
        } catch (error) {
            onError?.(error)
        } finally {
            loading = false
        }
    }

    onDestroy(() => {
        unsubscribeEventListeners?.()
    })

    let componentProps = $derived.by(() => {
        const filtered = {}
        Object.keys(restProps).forEach((key) => {
            if (modalPropNames.includes(key)) return
            if (key.startsWith('on') && typeof restProps[key] === 'function') return
            if (['href', 'method', 'data', 'as', 'headers', 'queryStringArrayFormat', 'navigate'].includes(key)) return

            filtered[key] = restProps[key]
        })
        return filtered
    })
</script>

<svelte:element
    this={as}
    {href}
    {...componentProps}
    onclick={handle}
>
    {@render children?.({ loading })}
</svelte:element>

// vue/src/ModalLink.vue
<script setup lang="ts">
import { modalPropNames, useModalStack } from './modalStack'
import { ref, provide, computed, watch, useAttrs, onBeforeUnmount } from 'vue'
import { only, rejectNullValues } from './helpers'
import { getConfig } from './config'

const props = defineProps({
    href: {
        type: String,
        required: true,
    },
    method: {
        type: String,
        default: 'get',
    },
    data: {
        type: Object,
        default: () => ({}),
    },
    as: {
        type: String,
        default: 'a',
    },
    headers: {
        type: Object,
        default: () => ({}),
    },
    queryStringArrayFormat: {
        type: String,
        default: 'brackets',
    },
    navigate: {
        type: Boolean,
        default: null,
    },
    // Passthrough to Modal.vue
    closeButton: {
        type: Boolean,
        required: false,
        default: null,
    },
    closeExplicitly: {
        type: Boolean,
        required: false,
        default: null,
    },
    maxWidth: {
        type: String,
        required: false,
        default: null,
    },
    paddingClasses: {
        type: [Boolean, String],
        required: false,
        default: null,
    },
    panelClasses: {
        type: [Boolean, String],
        required: false,
        default: null,
    },
    position: {
        type: String,
        required: false,
        default: null,
    },
    slideover: {
        type: Boolean,
        required: false,
        default: null,
    },
})

const loading = ref<boolean>(false)
const modalStack = useModalStack()
const modalContext = ref(null)

provide('modalContext', modalContext)

const emit = defineEmits(['after-leave', 'blur', 'close', 'error', 'focus', 'start', 'success'])
const isBlurred = ref<boolean>(false)

const shouldNavigate = computed(() => {
    return props.navigate ?? getConfig('navigate')
})

watch(
    () => modalContext.value?.onTopOfStack,
    (onTopOfStack) => {
        if (modalContext.value) {
            if (onTopOfStack && isBlurred.value) {
                emit('focus')
            } else if (!onTopOfStack) {
                emit('blur')
            }

            isBlurred.value = !onTopOfStack
        }
    },
)

const unsubscribeEventListeners = ref(null)

onBeforeUnmount(() => {
    unsubscribeEventListeners.value?.()
})

const $attrs = useAttrs()

function registerEventListeners() {
    unsubscribeEventListeners.value = modalContext.value.registerEventListenersFromAttrs($attrs)
}

watch(modalContext, (value, oldValue) => {
    if (value && !oldValue) {
        registerEventListeners()
        emit('success')
    }
})

function onClose() {
    emit('close')
}

function onAfterLeave() {
    modalContext.value = null
    emit('after-leave')
}

function handle() {
    if (loading.value) {
        return
    }

    if (!props.href.startsWith('#')) {
        loading.value = true
        emit('start')
    }

    modalStack
        .visit(
            props.href,
            props.method,
            props.data,
            props.headers,
            rejectNullValues(only(props, modalPropNames)),
            onClose,
            onAfterLeave,
            props.queryStringArrayFormat,
            shouldNavigate.value,
        )
        .then((context) => {
            modalContext.value = context
        })
        .catch((error) => emit('error', error))
        .finally(() => (loading.value = false))
}
</script>

<template>
    <component
        v-bind="$attrs"
        :is="as"
        :href="href"
        @click.prevent="handle"
    >
        <slot :loading="loading" />
    </component>
</template>
