// svelte/src/lib/WhenVisible.svelte
<script>
    // See: https://github.com/inertiajs/inertia/blob/master/packages/svelte/src/components/WhenVisible.svelte
    import { onMount, onDestroy, getContext } from 'svelte'

    let { data = null, params = null, buffer = 0, as = 'div', always = false, children, fallback } = $props()

    const modalContext = getContext('modalContext')

    if (!modalContext) {
        throw new Error('WhenVisible component must be used inside a Modal component')
    }

    let loaded = $state(false)
    let fetching = $state(false)
    let rootElement = $state(null)
    let observer = null

    function getReloadParams() {
        if (data) {
            return { only: Array.isArray(data) ? data : [data] }
        }

        if (!params) {
            throw new Error('You must provide either a `data` or `params` prop.')
        }

        return params
    }

    function observeElement() {
        if (!rootElement) {
            return
        }

        observer = new IntersectionObserver(
            (entries) => {
                if (!entries[0].isIntersecting) {
                    return
                }

                if (!always) {
                    observer.disconnect()
                }

                if (fetching) {
                    return
                }

                fetching = true
                const reloadParams = getReloadParams()

                modalContext.reload({
                    ...reloadParams,
                    onStart: () => {
                        fetching = true
                        reloadParams.onStart?.()
                    },
                    onFinish: () => {
                        loaded = true
                        fetching = false
                        reloadParams.onFinish?.()
                    },
                })
            },
            { rootMargin: `${buffer}px` },
        )

        observer.observe(rootElement)
    }

    onMount(() => {
        observeElement()
    })

    onDestroy(() => {
        observer?.disconnect()
    })
</script>

<svelte:element
    this={as}
    bind:this={rootElement}
>
    {#if loaded}
        {@render children?.()}
    {:else}
        {@render fallback?.()}
    {/if}
</svelte:element>

// vue/src/WhenVisible.vue
<script setup lang="ts">
// See: https://github.com/inertiajs/inertia/blob/48bcd21fb7daf467d0df1bfde2408f161f94a579/packages/vue3/src/whenVisible.ts
import { ref, onMounted, onUnmounted, inject } from 'vue'

const props = defineProps({
    data: [String, Array],
    params: Object,
    buffer: { type: Number, default: 0 },
    as: { type: String, default: 'div' },
    always: { type: Boolean, default: false },
})

const modalContext = inject('modalContext')

if (!modalContext) {
    throw new Error('Deferred component must be used inside a Modal component')
}

const loaded = ref<boolean>(false)
const fetching = ref<boolean>(false)
const rootElement = ref<Element | null>(null)
let observer = null

const getReloadParams = () => {
    if (props.data) {
        return { only: Array.isArray(props.data) ? props.data : [props.data] }
    }

    if (!props.params) {
        throw new Error('You must provide either a `data` or `params` prop.')
    }

    return props.params
}

const observeElement = () => {
    if (!rootElement.value) {
        return
    }

    observer = new IntersectionObserver(
        (entries) => {
            if (!entries[0].isIntersecting) {
                return
            }

            if (!props.always) {
                observer.disconnect()
            }

            if (fetching.value) {
                return
            }

            fetching.value = true
            const reloadParams = getReloadParams()

            modalContext.value.reload({
                ...reloadParams,
                onStart: () => {
                    fetching.value = true
                    reloadParams.onStart?.()
                },
                onFinish: () => {
                    loaded.value = true
                    fetching.value = false
                    reloadParams.onFinish?.()
                },
            })
        },
        { rootMargin: `${props.buffer}px` },
    )

    observer.observe(rootElement.value)
}

onMounted(observeElement)
onUnmounted(() => observer?.disconnect())
</script>

<template>
    <component
        :is="props.as"
        ref="rootElement"
    >
        <slot v-if="loaded"></slot>
        <slot
            v-else
            name="fallback"
        ></slot>
    </component>
</template>
