// demo-app/resources/js/Pages/MiddlewareCompatibility/Index.svelte
<script>
    import { ModalLink } from '@inertiaui/modal-svelte';
</script>

<div>
    <h1>Middleware Compatibility Test</h1>
    <p>This page tests that modals work correctly with custom middleware.</p>
    <br/>
    <ModalLink href="/middleware-compatibility/form" navigate>Open Modal</ModalLink>
</div>

// demo-app/resources/js/Pages/MiddlewareCompatibility/Index.jsx
import { ModalLink } from '@inertiaui/modal-react';

export default function Index() {
  return (
    <div>
      <h1>Middleware Compatibility Test</h1>
      <p>This page tests that modals work correctly with custom middleware.</p>
      <br/>
      <ModalLink href="/middleware-compatibility/form" navigate>Open Modal</ModalLink>
    </div>
  );
}
