// demo-app/resources/js/Pages/MiddlewareCompatibility/Index.svelte
<script>
    import { ModalLink } from '@inertiaui/modal-svelte';
</script>

<div>
    <h1>Middleware Compatibility Test</h1>
    <p>This page tests that modals work correctly with custom middleware.</p>
    <br/>
    <ModalLink href="/middleware-compatibility/form" navigate>Open Modal</ModalLink>
</div>

// demo-app/resources/js/Pages/MiddlewareCompatibility/Index.vue
<script setup>
import { ModalLink } from '@inertiaui/modal-vue'
</script>

<template>
    <div>
        <h1>Middleware Compatibility Test</h1>
        <p>This page tests that modals work correctly with custom middleware.</p>
        <br />
        <ModalLink href="/middleware-compatibility/form" navigate>Open Modal</ModalLink>
    </div>
</template>
