// vue/src/Deferred.vue
<script setup lang="ts">
// See: https://github.com/inertiajs/inertia/blob/48bcd21fb7daf467d0df1bfde2408f161f94a579/packages/vue3/src/deferred.ts
import { computed, inject } from 'vue'
import type { ModalInstance } from './types'

interface DeferredProps {
    data: string | string[]
}

const props = defineProps<DeferredProps>()

const modalContext = inject<ModalInstance | null>('modalContext')

if (!modalContext) {
    throw new Error('Deferred component must be used inside a Modal component')
}

const allKeysAreAvailable = computed(() => {
    const keys = Array.isArray(props.data) ? props.data : [props.data]

    return keys.every((key) => modalContext?.props[key] !== undefined)
})
</script>

<template>
    <slot v-if="allKeysAreAvailable" />

    <slot
        v-else
        name="fallback"
    />
</template>

// svelte/src/lib/Deferred.svelte
<script>
    // https://github.com/inertiajs/inertia/blob/master/packages/svelte/src/components/Deferred.svelte
    import { getContext } from 'svelte'

    let { data, children, fallback } = $props()

    if (!data) {
        throw new Error('`<Deferred>` requires a `data` prop to be a string or array of strings')
    }

    const modalContext = getContext('modalContext')

    if (!modalContext) {
        throw new Error('Deferred component must be used inside a Modal component')
    }

    const keys = Array.isArray(data) ? data : [data]

    let allKeysAreAvailable = $derived(keys.every((key) => modalContext.props[key] !== undefined))
</script>

{#if allKeysAreAvailable}
    {@render children?.()}
{:else}
    {@render fallback?.()}
{/if}
