// vue/src/ModalRenderer.vue
<script setup>
import { useModalStack } from './modalStack'
import { computed, provide } from 'vue'

const props = defineProps({
    index: {
        type: Number,
        required: true,
    },
})

const modalStack = useModalStack()

const modalContext = computed(() => {
    return modalStack.stack.value[props.index]
})

provide('modalContext', modalContext)
</script>

<template>
    <modalContext.component
        v-if="modalContext?.component"
        v-bind="modalContext.props"
        @modal-event="(event, ...args) => modalContext.emit(event, ...args)"
    />
</template>

// svelte/src/lib/ModalRenderer.svelte
<script>
    import { useModalStack } from './modalStack.svelte.js'
    import { setContext } from 'svelte'

    let { index } = $props()

    const modalStack = useModalStack()

    let modalContext = $derived(modalStack.stack[index])
    setContext('modalContext', modalContext)

    $effect(() => {
        modalContext = modalStack.stack[index]
    })

    $effect(() => {
        setContext('modalContext', modalContext)
    })

    let Page = $derived(modalContext?.component?.default)

    function handleModalEvent(event, ...args) {
        modalContext?.emit(event.type, ...args)
    }
</script>

{#if Page}
    <Page
        {...modalContext.props}
        onModalEvent={handleModalEvent}
    />
{/if}
